const PERMISSIONS = {
  VIEW_DASHBOARD: "view_dashboard",

  MANAGE_USERS: "manage_users",
  MANAGE_ROLES: "manage_roles",
  MANAGE_DEPARTMENTS: "manage_departments",
  MANAGE_SUPPLIERS: "manage_suppliers",
  MANAGE_CATEGORIES: "manage_categories",
  MANAGE_UNITS: "manage_units",
  MANAGE_STORES: "manage_stores",
  MANAGE_WAREHOUSES: "manage_warehouses",
  MANAGE_SHELVES: "manage_shelves",
  MANAGE_ITEMS: "manage_items",
  MANAGE_LOCATIONS: "manage_locations",

  RECEIVE_STOCK: "receive_stock",
  INSPECT_STOCK: "inspect_stock",
  VIEW_GRN: "view_grn",

  VIEW_STOCK: "view_stock",
  VIEW_SHELF_LIFE: "view_shelf_life",
  MANAGE_STOCK_CARDS: "manage_stock_cards",
  MANAGE_BIN_CARDS: "manage_bin_cards",
  TRANSFER_STOCK: "transfer_stock",
  STOCK_TAKING: "stock_taking",
  STOCK_ADJUSTMENT: "stock_adjustment",
  RETURN_STOCK: "return_stock",
  ISSUE_STOCK: "issue_stock",

  VIEW_ISSUE_VOUCHERS: "view_issue_vouchers",
  CREATE_ISSUE_VOUCHER: "create_issue_voucher",

  CREATE_REQUISITION: "create_requisition",
  UPDATE_REQUISITION: "update_requisition",
  SUBMIT_REQUISITION: "submit_requisition",
  VIEW_REQUISITIONS: "view_requisitions",
  APPROVE_REQUISITION: "approve_requisition",
  REJECT_REQUISITION: "reject_requisition",

  VIEW_PROCUREMENTS: "view_procurement",
  VIEW_PURCHASE_ORDERS: "view_purchase_order",
  VIEW_DELIVERIES: "view_deliveries",
  VIEW_PURCHASE_REQUISITIONS: "view_purchase_requisitions",
  CREATE_PURCHASE_REQUISITION: "create_purchase_requisition",
  UPDATE_PURCHASE_REQUISITION: "update_purchase_requisition",
  SUBMIT_PURCHASE_REQUISITION: "submit_purchase_requisition",
  APPROVE_PURCHASE_REQUISITION: "approve_purchase_requisition",
  REJECT_PURCHASE_REQUISITION: "reject_purchase_requisition",
  ASSIGN_PURCHASE_REQUISITION_SUPPLIER: "assign_purchase_requisition_supplier",

  VIEW_GATE_PASSES: "view_gate_pass",
  CREATE_GATE_PASS: "create_gate_pass",
  VERIFY_GATE_PASS: "verify_gate_pass",
  CONFIRM_GATE_PASS_EXIT: "confirm_gate_pass_exit",
  RECORD_DISPATCH: "record_dispatch",

  VIEW_VALUATION: "view_valuation",
  RECONCILE_STOCK: "reconcile_stock",

  VIEW_REPORTS: "view_reports",
  VIEW_AUDIT: "view_audit",

  MANAGE_NOTIFICATIONS: "manage_notifications",
  MANAGE_SETTINGS: "manage_settings",

  VIEW_STOCK_TAKING: "view_stock_taking",
  CREATE_STOCK_TAKING: "create_stock_taking",
  INVESTIGATE_DISCREPANCY: "investigate_discrepancy",
  APPROVE_STOCK_ADJUSTMENT: "approve_stock_adjustment",
  VIEW_SHELF_LIFE: "view_shelf_life",
  VIEW_EXPIRING_STOCK: "view_expiring_stock",
  VIEW_DISPOSALS: "view_disposals",
  CREATE_DISPOSAL_REQUEST: "create_disposal_request",
  INSPECT_DISPOSAL: "inspect_disposal",
  APPROVE_DISPOSAL: "approve_disposal",
  COMPLETE_DISPOSAL: "complete_disposal",
  COUNT_STOCK: "count_stock",
  VIEW_STOCK_CARDS: "view_stock_cards",
  VIEW_BIN_CARDS: "view_bin_cards",
  VIEW_STOCK_TRANSACTIONS: "view_stock_transactions",
  CREATE_STOCK_TRANSFER: "create_stock_transfer",
  COMPLETE_STOCK_TRANSFER: "complete_stock_transfer",
  VIEW_STOCK_ADJUSTMENTS: "view_stock_adjustments",
  REJECT_STOCK_ADJUSTMENT: "reject_stock_adjustment",
  VIEW_FINANCIAL_REPORTS: "view_financial_reports",
  VIEW_RECONCILIATION: "view_reconciliation",
  VIEW_NOTIFICATIONS: "view_notifications",
  VIEW_INVENTORY: "view_inventory",
  CREATE_ASSET: "create_asset",
  VIEW_ASSETS: "view_assets",
  ASSIGN_ASSET: "assign_asset",
  CONFIRM_GATE_PASS_EXIT: "confirm_gate_pass_exit",
  RECORD_DISPATCH: "record_dispatch",
  CREATE_MATERIAL_RETURN: "create_material_return",
  VIEW_MATERIAL_RETURNS: "view_material_returns",
  RECEIVE_MATERIAL_RETURN: "receive_material_return",
  INSPECT_MATERIAL_RETURN: "inspect_material_return",
  APPROVE_MATERIAL_RETURN: "approve_material_return",
  REJECT_MATERIAL_RETURN: "reject_material_return",
  CREATE_USER_CARD: "create_user_card",
  VIEW_USER_CARDS: "view_user_cards",
  SUBMIT_REQUISITION: "submit_requisition",
  UPDATE_REQUISITION: "update_requisition",
  REJECT_REQUISITION: "reject_requisition",
  COMPLETE_ISSUE: "complete_issue",
  CREATE_ISSUE: "create_issue",
  CREATE_ISSUE_VOUCHER: "create_issue_voucher",
  VIEW_ISSUE_VOUCHERS: "view_issue_vouchers",
  VIEW_ISSUING: "view_issuing",
};

export default PERMISSIONS;