import PERMISSIONS from "./permissions";

export const ROLES = {
  ADMINISTRATOR: "Administrator",
  PAO: "PAO",
  PROCUREMENT_OFFICER: "Procurement Officer",
  INSPECTOR: "Inspector",
  STOREKEEPER: "Storekeeper",
  STOCK_CLERK: "Stock Clerk",
  DEPARTMENT_USER: "Department User",
  DEPARTMENT_HEAD: "Department Head",
  ACCOUNTS_OFFICER: "Accounts Officer",
  STOCK_AUDITOR: "Stock Auditor",
  SECURITY_OFFICER: "Security Officer",
};

export const ROLE_LABELS = {
  [ROLES.ADMINISTRATOR]: "System Administrator",
  [ROLES.PAO]: "Property Administration Officer",
  [ROLES.PROCUREMENT_OFFICER]: "Procurement Officer",
  [ROLES.INSPECTOR]: "Inspector",
  [ROLES.STOREKEEPER]: "Storekeeper",
  [ROLES.STOCK_CLERK]: "Stock Clerk",
  [ROLES.DEPARTMENT_USER]: "Department User",
  [ROLES.DEPARTMENT_HEAD]: "Department Head",
  [ROLES.ACCOUNTS_OFFICER]: "Accounts Officer",
  [ROLES.STOCK_AUDITOR]: "Stock Auditor",
  [ROLES.SECURITY_OFFICER]: "Security Officer",
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMINISTRATOR]: ["*"],

  [ROLES.PAO]: Object.values(PERMISSIONS),

  [ROLES.PROCUREMENT_OFFICER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_SUPPLIERS,
    PERMISSIONS.MANAGE_ITEMS,
    PERMISSIONS.MANAGE_CATEGORIES,
    PERMISSIONS.MANAGE_UNITS,
    PERMISSIONS.VIEW_PROCUREMENTS,
    PERMISSIONS.VIEW_REQUISITIONS,
    PERMISSIONS.CREATE_REQUISITION,
    PERMISSIONS.APPROVE_REQUISITION,
    PERMISSIONS.VIEW_PURCHASE_ORDERS,
    PERMISSIONS.VIEW_DELIVERIES,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_PURCHASE_REQUISITIONS,
    PERMISSIONS.CREATE_PURCHASE_REQUISITION,
    PERMISSIONS.UPDATE_PURCHASE_REQUISITION,
    PERMISSIONS.SUBMIT_PURCHASE_REQUISITION,
    PERMISSIONS.APPROVE_PURCHASE_REQUISITION,
    PERMISSIONS.REJECT_PURCHASE_REQUISITION,
    PERMISSIONS.ASSIGN_PURCHASE_REQUISITION_SUPPLIER,
  ],

  [ROLES.INSPECTOR]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.RECEIVE_STOCK,
    PERMISSIONS.INSPECT_STOCK,
    PERMISSIONS.VIEW_GRN,
    PERMISSIONS.VIEW_STOCK,
    PERMISSIONS.VIEW_REPORTS,
  ],

  [ROLES.STOREKEEPER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.RECEIVE_STOCK,
    PERMISSIONS.VIEW_GRN,
    PERMISSIONS.VIEW_STOCK,
    PERMISSIONS.MANAGE_STOCK_CARDS,
    PERMISSIONS.MANAGE_BIN_CARDS,
    PERMISSIONS.ISSUE_STOCK,
    PERMISSIONS.RETURN_STOCK,
    PERMISSIONS.TRANSFER_STOCK,
    PERMISSIONS.VIEW_REQUISITIONS,
    PERMISSIONS.CREATE_GATE_PASS,
    PERMISSIONS.VIEW_REPORTS,
  ],

  [ROLES.STOCK_CLERK]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_STOCK,
    PERMISSIONS.MANAGE_STOCK_CARDS,
    PERMISSIONS.MANAGE_BIN_CARDS,
    PERMISSIONS.TRANSFER_STOCK,
    PERMISSIONS.STOCK_TAKING,
    PERMISSIONS.VIEW_VALUATION,
    PERMISSIONS.RECONCILE_STOCK,
    PERMISSIONS.VIEW_REPORTS,
  ],

  [ROLES.DEPARTMENT_USER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_STOCK,
    PERMISSIONS.VIEW_REQUISITIONS,
    PERMISSIONS.CREATE_REQUISITION,
  ],

  [ROLES.DEPARTMENT_HEAD]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_STOCK,
    PERMISSIONS.VIEW_REQUISITIONS,
    PERMISSIONS.CREATE_REQUISITION,
    PERMISSIONS.APPROVE_REQUISITION,
    PERMISSIONS.VIEW_REPORTS,
  ],

  [ROLES.ACCOUNTS_OFFICER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_VALUATION,
    PERMISSIONS.RECONCILE_STOCK,
    PERMISSIONS.VIEW_REPORTS,
  ],

  [ROLES.STOCK_AUDITOR]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_STOCK,
    PERMISSIONS.STOCK_TAKING,
    PERMISSIONS.VIEW_VALUATION,
    PERMISSIONS.RECONCILE_STOCK,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_AUDIT,
  ],

  [ROLES.SECURITY_OFFICER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VERIFY_GATE_PASS,
    PERMISSIONS.VIEW_REPORTS,
  ],
};