import { useEffect, useMemo, useState, useContext } from "react";
import { useNavigate } from "react-router-dom";
import AuthContext from "../../context/AuthContext";

import PageHeader from "../../components/common/PageHeader";
import SearchBar from "../../components/common/SearchBar";
import EmptyState from "../../components/common/EmptyState";

import procurementData from "./procurementData";

import "./procurement.css";

function Procurement() {
  const navigate = useNavigate();
  const { hasPermission } = useContext(AuthContext);
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState("All");
  const [overview, setOverview] = useState({
    summary: {
      purchaseRequisitions: 0,
      pendingRequisitions: 0,
      purchaseOrders: 0,
      activeOrders: 0,
      pendingDeliveries: 0,
      suppliers: 0,
    },
    workflow: [],
  });
  const [activities, setActivities] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    async function loadProcurement() {
      setLoading(true);
      setError("");

      try {
        const overviewResult = await procurementData.getOverview();

        setOverview(overviewResult || { summary: { purchaseRequisitions: 0, pendingRequisitions: 0, purchaseOrders: 0, activeOrders: 0, pendingDeliveries: 0, suppliers: 0 }, workflow: [] });

        // Use the recent activities generated by the backend overview endpoint
        // It now legitimately encompasses requisitions, purchase orders, and deliveries
        const backendActivities = overviewResult?.recentActivities || [];

        // Map backend dates if necessary to strings
        setActivities(backendActivities.map(activity => ({
          ...activity,
          date: new Date(activity.date).toLocaleDateString()
        })));
      } catch (requestError) {
        setError(requestError.message);
      } finally {
        setLoading(false);
      }
    }

    loadProcurement();
  }, []);

  const filteredActivities = useMemo(() => {
    const value = search.trim().toLowerCase();

    return activities.filter((activity) => {
      const matchesSearch =
        !value ||
        activity.reference?.toLowerCase().includes(value) ||
        activity.type?.toLowerCase().includes(value) ||
        activity.requester?.toLowerCase().includes(value) ||
        activity.supplier?.toLowerCase().includes(value);

      const matchesStatus = statusFilter === "All" || activity.status === statusFilter;
      return matchesSearch && matchesStatus;
    });
  }, [activities, search, statusFilter]);

  const clearFilters = () => {
    setSearch("");
    setStatusFilter("All");
  };

  // Derive available statuses for the dropdown from the actual loaded data
  const availableStatuses = useMemo(() => {
    const statuses = new Set(activities.map(a => a.status));
    return Array.from(statuses).sort();
  }, [activities]);

  if (loading) {
    return (
      <div className="page-container procurement-page">
        <PageHeader title="Procurement Overview" description="Monitor purchasing activities, requisitions, purchase orders, and supplier deliveries." />
        <div style={{ marginTop: "20px", padding: "20px", background: "#fff", borderRadius: "8px", border: "1px solid #e5e7eb" }}>
          Loading procurement data...
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="page-container procurement-page">
        <PageHeader title="Procurement Overview" description="Monitor purchasing activities, requisitions, purchase orders, and supplier deliveries." />
        <EmptyState title="Error Loading Data" message={error} />
      </div>
    );
  }

  return (
    <div className="procurement-page">

      <PageHeader
        title="Procurement Overview"
        description="Monitor purchasing activities, requisitions, purchase orders, and supplier deliveries."
      />

      <div className="summary-grid">
        <div className="summary-card">
          <span className="summary-label">Purchase Requisitions</span>
          <strong className="summary-value">{overview.summary.purchaseRequisitions}</strong>
          <small>{overview.summary.pendingRequisitions} pending approval</small>
        </div>

        <div className="summary-card">
          <span className="summary-label">Purchase Orders</span>
          <strong className="summary-value">{overview.summary.purchaseOrders}</strong>
          <small>{overview.summary.activeOrders} active orders</small>
        </div>

        <div className="summary-card">
          <span className="summary-label">Pending Deliveries</span>
          <strong className="summary-value">{overview.summary.pendingDeliveries}</strong>
          <small>Awaiting receipt</small>
        </div>

        <div className="summary-card">
          <span className="summary-label">Suppliers</span>
          <strong className="summary-value">{overview.summary.suppliers}</strong>
          <small>Active suppliers</small>
        </div>
      </div>

      <div style={{ marginTop: "24px" }}>
        <div className="page-header">
          <div>
            <h2>Requisition Workflow</h2>
            <p>Current status of purchase requisitions.</p>
          </div>
        </div>
      </div>

      {overview.workflow && overview.workflow.length > 0 ? (
        <div className="summary-grid procurement-workflow-section">
          {overview.workflow.map((stage) => (
            <div className="summary-card" key={stage.stage}>
              <span className="summary-label">{stage.stage}</span>
              <strong className="summary-value">{stage.count}</strong>
              <small>{stage.description || "In progress"}</small>
            </div>
          ))}
        </div>
      ) : (
        <div className="procurement-workflow-section" style={{ marginTop: "16px", padding: "20px", background: "#ffffff", borderRadius: "12px", border: "1px solid #e5e7eb" }}>
          <EmptyState title="No requisition workflow data available" message="There are currently no active purchase requisitions in the workflow." />
        </div>
      )}

      <div className="master-page" style={{ marginTop: "24px" }}>
        <div className="page-header">
          <div>
            <h2>Recent Procurement Activity</h2>
            <p>Latest procurement requests and updates.</p>
          </div>


        </div>

        <div className="toolbar">
          <div className="toolbar-left">
            <SearchBar value={search} onChange={setSearch} placeholder="Search procurement..." />
            <select className="filter-select" value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}>
              <option value="All">All Status</option>
              {availableStatuses.map(status => (
                <option key={status} value={status}>
                  {status}
                </option>
              ))}
            </select>
          </div>

          {search || statusFilter !== "All" ? (
            <button type="button" className="secondary-button" onClick={clearFilters}>
              Clear
            </button>
          ) : null}
        </div>

        {filteredActivities.length === 0 ? (
          <EmptyState title="No procurement activity found" message="Try adjusting the filters." />
        ) : (
          <div className="data-table-wrapper">
            <table className="data-table">
              <thead>
                <tr>
                  <th>Reference</th>
                  <th>Type</th>
                  <th>Requester</th>
                  <th>Supplier</th>
                  <th>Date</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {filteredActivities.map((activity) => (
                  <tr key={activity.id}>
                    <td>{activity.reference}</td>
                    <td>{activity.type}</td>
                    <td>{activity.requester}</td>
                    <td>{activity.supplier}</td>
                    <td>{activity.date}</td>
                    <td><span className="status-badge">{activity.status}</span></td>
                  </tr>
                ))}
              </tbody>
            </table>

          </div>
        )}
      </div>
    </div >
  );
}

export default Procurement;
