/**
 * Permission constants for type-safe permission checks
 * Use these constants instead of magic strings to prevent typos
 */
export const PERMISSIONS = {
  // User Management
  MANAGE_USERS: "MANAGE_USERS",
  VIEW_USERS: "VIEW_USERS",
  
  // Inventory Management
  MANAGE_ITEMS: "MANAGE_ITEMS",
  VIEW_ITEMS: "VIEW_ITEMS",
  
  // Stock Operations
  MANAGE_RECEIPTS: "MANAGE_RECEIPTS",
  VIEW_RECEIPTS: "VIEW_RECEIPTS",
  APPROVE_RECEIPTS: "APPROVE_RECEIPTS",
  
  MANAGE_ISSUES: "MANAGE_ISSUES",
  VIEW_ISSUES: "VIEW_ISSUES",
  APPROVE_ISSUES: "APPROVE_ISSUES",
  
  // Requisitions
  CREATE_REQUISITION: "CREATE_REQUISITION",
  VIEW_REQUISITIONS: "VIEW_REQUISITIONS",
  APPROVE_REQUISITIONS: "APPROVE_REQUISITIONS",
  
  // Transfers
  MANAGE_TRANSFERS: "MANAGE_TRANSFERS",
  VIEW_TRANSFERS: "VIEW_TRANSFERS",
  
  // Reports
  VIEW_REPORTS: "VIEW_REPORTS",
  EXPORT_REPORTS: "EXPORT_REPORTS",
  
  // Settings
  MANAGE_CATEGORIES: "MANAGE_CATEGORIES",
  MANAGE_SUPPLIERS: "MANAGE_SUPPLIERS",
  MANAGE_STORES: "MANAGE_STORES",
  MANAGE_ROLES: "MANAGE_ROLES",
  
  // Audit
  VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];
